os:
  - linux

php:
 - 7.2
 - 7.3

addons:
  mariadb: '10.2'

before_install:
- mysql -e 'create database IF NOT EXISTS ukts_core;' -uroot
- sudo apt-get update
- composer install --prefer-dist --no-interaction --optimize-autoloader --no-suggest
- cp .env.example .env
- php artisan key:generate
- php artisan migrate -vvv -n

before_script:
- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
  ./cc-test-reporter before-build;
  fi

script:
- vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml
